### ISSUE TITLE
Trained Models

### ISSUE THREAD

**Issue by ujwalakoriraj** [mease/turning_heads#1]
Could you please provide the trained model of TP-GAN? I have tried training the model for 3 times now, and each time the kernel restarts at the 300th or the 400th epoch. Please provide the trained model of the TP-GAN.

**Comment by mease** [comment]
Here you go: https://drive.google.com/file/d/1wj3KBtJIenO25StmxQkttUslWE1tccbJ/view?usp=sharing

It is 2GB in size. Get it while you can, since I will probably take it down at some point since drive space is limited.

For training, if you are using Google CoLab, the kernel will probably always restart before training finishes. You could try training in small stages, saving off checkpoints and reloading them each session. But training on a local machine with GPU is recommended.

**Comment by ujwalakoriraj** [comment]
Thank you very much.
